local DiceArea = {
	--组合投区
	NOTE_TOTLE_COUNT_FOUR =15,
	NOTE_TOTLE_COUNT_FIVE =16,
	NOTE_TOTLE_COUNT_SIX =17,
	NOTE_TOTLE_COUNT_SEVEN =18,
	NOTE_TOTLE_COUNT_EIGHT=19,
	NOTE_TOTLE_COUNT_NINE = 20,
	NOTE_TOTLE_COUNT_TEN = 21,
	NOTE_TOTLE_COUNT_ELEVEN = 22,
	NOTE_TOTLE_COUNT_TWELVE = 23,
	NOTE_TOTLE_COUNT_THIRTEEN = 24,
	NOTE_TOTLE_COUNT_FOURTEEN = 25,
	NOTE_TOTLE_COUNT_FIFTEEN = 26,
	NOTE_TOTLE_COUNT_SIXTEEN = 27,
	NOTE_TOTLE_COUNT_SEVENTEEN = 28,

	--豹子投区
	NOTE_WEI_ONE  =8,
	NOTE_WEI_TWO = 9,
	NOTE_WEI_THREE =10,
	NOTE_WEI_FOUR =11,
	NOTE_WEI_FIVE =12,
	NOTE_WEI_SIX =13,

	NOTE_WEI_ALL =14,

	--单骰子区
	NOTE_SINGLE_ONE = 44,
	NOTE_SINGLE_TWO  = 45,
	NOTE_SINGLE_THREE = 46,
	NOTE_SINGLE_FOUR = 47,
	NOTE_SINGLE_FIVE = 48,
	NOTE_SINGLE_SIX = 49,

	--单数区域		
	NOTE_SINGLE = 50,

	--大
	NOTE_BIG  = 1,
	
	--双数区域
	NOTE_DOUBLE = 51,
	
	--小
	NOTE_SMALL = 0,
	
};

return DiceArea;